Exit workflow if curl failed

diff --git a/.github/workflows/update-chromeos-kernel.yml b/.github/workflows/update-chromeos-kernel.yml
--- a/.github/workflows/update-chromeos-kernel.yml
+++ b/.github/workflows/update-chromeos-kernel.yml
@@ -28,6 +28,11 @@ jobs:
         run: |
           # Download remote sha
           latest_tag=$(curl -s https://api.github.com/repos/eupnea-linux/chromeos-kernel/releases/latest | jq -r '.tag_name')
+          # fail if curl result is empty
+          if [[ -z "$latest_tag" ]]; then
+              echo "latest_tag is empty"
+              exit 1
+          fi
           
           # Check remote tag against cached one
           match_results=$([[ "$(cat cache/chromeos_kernel_tag-cache.txt)" == "$latest_tag" ]] && echo "true" || echo "false")
diff --git a/.github/workflows/update-keyd.yml b/.github/workflows/update-keyd.yml
--- a/.github/workflows/update-keyd.yml
+++ b/.github/workflows/update-keyd.yml
@@ -30,6 +30,11 @@ jobs:
         run: |
           # Download remote sha
           latest_sha=$(curl -s https://api.github.com/repos/rvaiya/keyd/commits/main | jq -r '.sha')
+          # fail if curl result is empty
+          if [[ -z "$latest_sha" ]]; then
+              echo "latest_tag is empty"
+              exit 1
+          fi
           
           # Check remote sha against cached one
           match_results=$([[ "$(cat cache/keyd-cache.txt)" == "$latest_sha" ]] && echo "true" || echo "false")
diff --git a/.github/workflows/update-utils.yml b/.github/workflows/update-utils.yml
--- a/.github/workflows/update-utils.yml
+++ b/.github/workflows/update-utils.yml
@@ -30,7 +30,17 @@ jobs:
         run: |
           # Download remote shas
           postinstall_latest_sha=$(curl -s https://api.github.com/repos/eupnea-linux/eupnea-utils/commits/main | jq -r '.sha')
+          # fail if curl result is empty
+          if [[ -z "$postinstall_latest_sha" ]]; then
+              echo "latest_tag is empty"
+              exit 1
+          fi
           audio_latest_sha=$(curl -s https://api.github.com/repos/eupnea-linux/audio-scripts/commits/main | jq -r '.sha')
+          # fail if curl result is empty
+          if [[ -z "$audio_latest_sha" ]]; then
+              echo "latest_tag is empty"
+              exit 1
+          fi
           
           # Check remote shas against cached ones
           postinstall_match_results=$([[ "$(cat cache/utils_sha-cache.txt | head -1)" == "$postinstall_latest_sha" ]] && echo "true" || echo "false")
